name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test


      - name: Upload start.sh file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.BIT_SSH_KEY }}
          port: 22
          source: "start.sh"
          target: "/home/ec2-user/"
          debug: true

      - name: Upload JAR file to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.BIT_SSH_KEY }}
          port: 22
          source: "build/libs/bitcoinlion-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/"
          debug: true

      - name: SSH to EC2 and run commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.BIT_SSH_KEY }}
          port: 22
          script: |
            mv build/libs/bitcoinlion-0.0.1-SNAPSHOT.jar .
            chmod 755 start.sh
            ./start.sh
            
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        if: always() # 성공/실패 여부와 상관없이 실행
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: "GitHub-Bot"
          DISCORD_AVATAR: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        with:
          args: '배포가 종료되었습니다! 상태: ${{ job.status }}'